version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Zxcvbnm@2000
      MYSQL_DATABASE: order_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:latest
    container_name: redis-services
    restart: always
    ports:
      - "6379:6379"

  eureka-server:
    image: 573051981280.dkr.ecr.ap-south-1.amazonaws.com/eureka-server:latest
    container_name: eureka-server
    ports:
      - "8761:8761"
    depends_on:
      - mysql

  api-gateway:
    image: 573051981280.dkr.ecr.ap-south-1.amazonaws.com/api-gateway:latest
    container_name: api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - eureka-server

  product-service:
    image: 573051981280.dkr.ecr.ap-south-1.amazonaws.com/product-service:latest
    container_name: product-service
    ports:
      - "8081:8081"
    depends_on:
      - mysql
      - eureka-server

  order-service:
    image: 573051981280.dkr.ecr.ap-south-1.amazonaws.com/order-service:latest
    container_name: order-service
    ports:
      - "8082:8082"
    depends_on:
      - mysql
      - eureka-server

volumes:
  mysql_data:
