version: '3.8'

services:
  eureka-server:
    image: 573051981280.dkr.ecr.ap-south-1.amazonaws.com/eureka-server:latest
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - microservices-net
    environment:
      EUREKA_INSTANCE_HOSTNAME: ${EC2_PUBLIC_IP}
      EUREKA_CLIENT_REGISTER_WITH_EUREKA: "false"
      EUREKA_CLIENT_FETCH_REGISTRY: "false"
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://${EC2_PUBLIC_IP}:8761/eureka/


  api-gateway:
    image: 573051981280.dkr.ecr.ap-south-1.amazonaws.com/api-gateway:latest
    container_name: api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - eureka-server
    networks:
      - microservices-net
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://${EC2_PUBLIC_IP}:8761/eureka/


  product-service:
    image: 573051981280.dkr.ecr.ap-south-1.amazonaws.com/product-service:latest
    container_name: product-service
    ports:
      - "8082:8080"
    depends_on:
      - eureka-server
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://${DB_HOST}:3306/product_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://${EC2_PUBLIC_IP}:8761/eureka/
    networks:
      - microservices-net


  order-service:
    image: 573051981280.dkr.ecr.ap-south-1.amazonaws.com/order-service:latest
    container_name: order-service
    ports:
      - "8083:8080"
    depends_on:
      - eureka-server
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://${DB_HOST}:3306/product_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://${EC2_PUBLIC_IP}:8761/eureka/
    networks:
      - microservices-net

  auth-service:
    image: 573051981280.dkr.ecr.ap-south-1.amazonaws.com/auth-service:latest
    container_name: auth-service
    ports:
      - "8089:8080"
    depends_on:
      - eureka-server
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://${DB_HOST}:3306/product_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://${EC2_PUBLIC_IP}:8761/eureka/
    networks:
      - microservices-net


networks:
  microservices-net:
    driver: bridge
